# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2019-07-21 11:56
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20190720_2033'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='mygalary_image',
            field=models.ImageField(default=django.utils.timezone.now, upload_to='mygalary/'),
            preserve_default=False,
        ),
    ]
